frr version 8.4
frr defaults traditional
hostname hq-r1
!
interface eth1
 ip address 203.0.113.2/24
!
interface eth2
 ip address 10.255.1.1/30
!
interface lo
 ip address 10.100.0.1/32
!
router bgp 65001
 bgp router-id 10.100.0.1
 no bgp ebgp-requires-policy
 neighbor 203.0.113.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.10.0.0/16
 exit-address-family
!
router ospf
 ospf router-id 10.100.0.1
 network 10.255.1.0/30 area 0
 network 10.100.0.1/32 area 0
 default-information originate
!
ip route 10.10.0.0/16 Null0
!
line vty
!
end