import { Activity, AlertTriangle, ArrowDown, ArrowRight, Ban, Boxes, Cable, Check, ChevronRight, CircleDot, Clock3, Code2, Container, Cpu, Database, ExternalLink, FileCode2, Filter, Globe2, HardDrive, Info, Layers3, LockKeyhole, Menu, Network, Radio, RefreshCw, Router, Route as RouteIcon, Search, Server, Shield, SlidersHorizontal, TerminalSquare, Wifi, X, Zap, Square, Play, GitBranch, ListFilter, CircleDashed } from "lucide-react";
import { aclPolicies, configs, demoTelemetry, devices, events, links, navItems, topologyPositions, vlans, type DeviceRecord, type LinkRecord, type LinkState } from "@/lib/acmeData";
import { trpc } from "@/lib/trpc";
import { liveState, StatusDot, StateBadge, Icon, Panel, Header, Sidebar, PageHeader, StatCell } from "@/components/NetworkPrimitives";
export function EventRow({ event }: { event: (typeof events)[number] }) { return <div className="px-4 py-3"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><span className={`h-1.5 w-1.5 shrink-0 rounded-full ${event.kind === "routing" ? "bg-[#62d2a3]" : event.kind === "security" ? "bg-[#e1b86c]" : "bg-[#75bce0]"}`} /><span className="truncate text-[11px] font-semibold text-[#cddde4]">{event.title}</span></div><span className="mono shrink-0 text-[10px] text-[#6d8591]">{event.time}</span></div><div className="mt-1 pl-3.5 text-[10px] text-[#758b96]">{event.detail}</div></div>; }

export function EventsPage({ liveEvents = [], onEventSelect }: { liveEvents?: Array<(typeof events)[number]>; onEventSelect?: (event: (typeof events)[number]) => void }) { const timeline = [...liveEvents, ...events]; return <div><PageHeader eyebrow="Audit / Events" title="Event timeline" detail="State events from the seeded WAN lab and static configuration events from the supplied campus source. Live mode replaces seeded telemetry when available." actions={<StateBadge label="APPEND-ONLY VIEW" state="modeled" />} /><Panel><div className="divide-y divide-[#21313a]">{timeline.map((event, index) => <button type="button" key={`${event.title}-${index}`} onClick={() => onEventSelect?.(event)} className="grid w-full gap-3 px-5 py-4 text-left transition-colors hover:bg-[#12232d] sm:grid-cols-[74px_16px_1fr_110px]"><div className="mono text-[11px] text-[#78909d]">{event.time}</div><div className="relative flex justify-center"><span className={`mt-1.5 h-2 w-2 rounded-full ${event.kind === "routing" ? "bg-[#62d2a3]" : event.kind === "security" ? "bg-[#e1b86c]" : "bg-[#75bce0]"}`} />{index < timeline.length - 1 && <span className="absolute top-4 h-full w-px bg-[#263741]" />}</div><div><div className="text-[12px] font-semibold text-[#d5e2e8]">{event.title}</div><div className="mt-1 text-[11px] text-[#859aa5]">{event.detail}</div><div className="mono mt-2 text-[10px] text-[#647b88]">source: {event.source}</div></div><div className="text-left sm:text-right"><span className={`border px-2 py-1 text-[9px] font-bold tracking-[.1em] ${event.mode === "DEMO" ? "border-[#66542f] text-[#ddbc78]" : event.mode === "LIVE" ? "border-[#2f6c57] text-[#67cda0]" : "border-[#344751] text-[#93a8b3]"}`}>{event.mode}</span></div></button>)}</div></Panel></div>; }

export default EventsPage;
