import { Activity, AlertTriangle, ArrowDown, ArrowRight, Ban, Boxes, Cable, Check, ChevronRight, CircleDot, Clock3, Code2, Container, Cpu, Database, ExternalLink, FileCode2, Filter, Globe2, HardDrive, Info, Layers3, LockKeyhole, Menu, Network, Radio, RefreshCw, Router, Route as RouteIcon, Search, Server, Shield, SlidersHorizontal, TerminalSquare, Wifi, X, Zap, Square, Play, GitBranch, ListFilter, CircleDashed } from "lucide-react";
import { aclPolicies, configs, demoTelemetry, devices, events, links, navItems, topologyPositions, vlans, type DeviceRecord, type LinkRecord, type LinkState } from "@/lib/acmeData";
import { trpc } from "@/lib/trpc";
import { liveState, StatusDot, StateBadge, Icon, Panel, Header, Sidebar, PageHeader, StatCell } from "@/components/NetworkPrimitives";
import { RoutePath } from "@/components/RoutePath";
import { EventRow } from "./Events";

const nodeById = Object.fromEntries(devices.map((device) => [device.id, device]));
export function Overview({ mode, live, liveEvents = [], setSelected, go }: { mode: "DEMO" | "LIVE"; live: any; liveEvents?: Array<(typeof events)[number]>; setSelected: (id: string) => void; go: (path: string) => void }) {
  const telemetry = mode === "DEMO" ? demoTelemetry : live;
  const reachable = mode === "DEMO" || live?.reachable;
  return <div>
    <PageHeader eyebrow="Operations / Overview" title="Network health" detail="A factual view of the ACME enterprise model and its separate Docker + Containerlab routing validation lab." actions={<div className="flex items-center gap-2"><StateBadge label={`${mode} DATA`} state={mode === "DEMO" ? "modeled" : reachable ? "up" : "unknown"} /><button onClick={() => go("/topology")} className="flex items-center gap-2 border border-[#395366] bg-[#142532] px-3 py-2 text-[11px] font-semibold text-[#b9dbec] hover:bg-[#19313f]">Open topology <ArrowRight size={14} /></button></div>} />
    <div className="panel mb-5 grid grid-cols-2 gap-y-5 px-4 py-4 md:grid-cols-4 xl:grid-cols-8">
      <StatCell label="Campus" value="MODELED" hint="16 devices" state="modeled" /><StatCell label="WAN lab" value={mode} hint={mode === "DEMO" ? "seeded state" : "runtime telemetry"} state={mode === "DEMO" ? "modeled" : reachable ? "up" : "unknown"} /><StatCell label="Docker" value={telemetry?.docker ?? "UNKNOWN"} hint="backend adapter" state={telemetry?.docker === "ONLINE" ? "up" : "unknown"} /><StatCell label="Containerlab" value={telemetry?.containerlab ?? "UNKNOWN"} hint="acme-wan-lab" state={telemetry?.containerlab === "ONLINE" ? "up" : "unknown"} /><StatCell label="BGP" value={telemetry?.bgp?.state ?? "UNKNOWN"} hint="isp-peer ↔ hq-r1" state={telemetry?.bgp?.state} /><StatCell label="OSPF" value={telemetry?.ospf?.state ?? "UNKNOWN"} hint="area 0" state={telemetry?.ospf?.state} /><StatCell label="Firewall" value="MODELED" hint="ASA1 / NAT enabled" state="modeled" /><StatCell label="Links" value="15 + 2" hint="campus + live lab" state="modeled" />
    </div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.85fr)]">
      <Panel title="Topology at a glance" eyebrow="Campus + live routing lab" action={<button onClick={() => go("/topology")} className="text-[10px] font-bold tracking-[.12em] text-[#79b9d9] hover:text-[#a5dbf3]">INSPECT <ArrowRight size={12} className="ml-1 inline" /></button>}><div className="p-3"><MiniTopology onSelect={setSelected} /></div></Panel>
      <div className="space-y-5"><Panel title="Default route path" eyebrow="0.0.0.0/0"><RoutePath telemetry={telemetry} mode={mode} compact /></Panel><Panel title="Current events" eyebrow="State stream" action={<button onClick={() => go("/events")} className="text-[10px] font-bold tracking-[.12em] text-[#79b9d9]">VIEW ALL</button>}><div className="divide-y divide-[#20303a]">{[...liveEvents, ...events].slice(0, 4).map((event, index) => <EventRow key={`${event.mode}-${event.time}-${event.title}-${index}`} event={event} />)}</div></Panel></div>
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3"><Panel title="Campus model" eyebrow="Cisco-style modeled topology"><ModelSummary setSelected={setSelected} /></Panel><Panel title="WAN lab contract" eyebrow="Runtime separation"><div className="space-y-3 p-4 text-[11px] leading-5 text-[#8ba0ae]"><div className="flex gap-3"><Boxes size={16} className="mt-0.5 text-[#77bce0]" /><span>Campus devices are source-model entities. They are not represented as Docker containers.</span></div><div className="flex gap-3"><Container size={16} className="mt-0.5 text-[#77bce0]" /><span>FRR nodes are additional live lab entities used to validate eBGP and OSPF behavior.</span></div></div></Panel><Panel title="Security posture" eyebrow="Configured scope only"><div className="grid grid-cols-2 gap-3 p-4"><div><div className="data-label">NAT</div><div className="mt-1 text-[12px] font-semibold text-[#d8e4eb]">Dynamic interface</div></div><div><div className="data-label">ASA inside</div><div className="mono mt-1 text-[12px] text-[#d8e4eb]">SEC 100</div></div><div><div className="data-label">ASA outside</div><div className="mono mt-1 text-[12px] text-[#d8e4eb]">SEC 0</div></div><div><div className="data-label">ACL sets</div><div className="mono mt-1 text-[12px] text-[#d8e4eb]">03 loaded</div></div></div></Panel></div>
  </div>;
}

export function ModelSummary({ setSelected }: { setSelected: (id: string) => void }) {
  return <div className="grid grid-cols-2 gap-2 p-4">{["core-sw1", "asa1", "br1-core", "access-sw1"].map((id) => { const d = nodeById[id]; return <button key={id} onClick={() => setSelected(id)} className="border border-[#263844] bg-[#101b23] p-3 text-left hover:border-[#4e7890]"><div className="mb-3 flex items-center justify-between"><Icon name={d.category === "edge" ? "shield" : d.category === "core" ? "network" : "server"} size={16} /><StatusDot state="modeled" /></div><div className="text-[11px] font-bold text-[#d8e7ee]">{d.label}</div><div className="mt-1 text-[10px] text-[#728793]">{d.role}</div></button> })}</div>;
}

export function MiniTopology({ onSelect }: { onSelect: (id: string) => void }) {
  return <div className="relative h-[292px] overflow-hidden border border-[#23343e] bg-[#0b1319] technical-grid"><svg viewBox="0 0 900 292" className="h-full w-full min-w-[760px]"><g opacity=".8">{[[88,90,210,90],[210,90,340,90],[340,90,480,90],[480,90,630,90],[480,90,480,196],[480,196,630,196],[630,196,760,196],[630,90,760,38],[630,90,760,83],[630,90,760,128],[630,90,760,173],[630,90,760,218],[630,90,760,263],[760,38,850,38],[760,83,850,83],[760,128,850,128],[760,173,850,173],[760,218,850,218],[760,263,850,263]].map(([x1,y1,x2,y2], i) => <line key={i} x1={x1} y1={y1} x2={x2} y2={y2} stroke="#506773" strokeWidth="1" strokeDasharray={i > 5 ? "3 4" : undefined} />)}<line x1="230" y1="252" x2="400" y2="252" stroke="#5cc5e6" strokeWidth="2" /><line x1="400" y1="252" x2="570" y2="252" stroke="#5cc5e6" strokeWidth="2" /></g><g className="font-mono" fontSize="9" fill="#d5e3ea"><TopoNode x={55} y={62} label="ISP" icon="globe" tone="wan" onClick={() => onSelect("isp-cloud-1")} /><TopoNode x={180} y={62} label="R1" icon="router" tone="edge" onClick={() => onSelect("r1")} /><TopoNode x={310} y={62} label="ASA1" icon="shield" tone="edge" onClick={() => onSelect("asa1")} /><TopoNode x={450} y={62} label="CORE-SW1" icon="core" tone="core" onClick={() => onSelect("core-sw1")} /><TopoNode x={600} y={62} label="ACCESS" icon="switch" tone="access" onClick={() => onSelect("access-sw1")} /><TopoNode x={450} y={168} label="BR1-CORE" icon="core" tone="core" onClick={() => onSelect("br1-core")} /><TopoNode x={600} y={168} label="BR1-ACCSS" icon="switch" tone="access" onClick={() => onSelect("br1-accss")} /><TopoNode x={210} y={224} label="isp-peer" icon="live" tone="live" onClick={() => onSelect("isp-peer")} /><TopoNode x={380} y={224} label="hq-r1" icon="live" tone="live" onClick={() => onSelect("hq-r1")} /><TopoNode x={550} y={224} label="br-r1" icon="live" tone="live" onClick={() => onSelect("br-r1")} /></g></svg><div className="absolute bottom-2 left-3 flex items-center gap-4 text-[9px] tracking-[.1em] text-[#718693]"><span><i className="mr-1.5 inline-block h-1.5 w-5 bg-[#506773]" />MODELED LINK</span><span><i className="mr-1.5 inline-block h-[2px] w-5 bg-[#5cc5e6]" />LIVE PATH</span></div></div>;
}

export function TopoNode({ x, y, label, icon, tone, onClick }: { x: number; y: number; label: string; icon: string; tone: string; onClick: () => void }) {
  const color = tone === "live" ? "#65d5a6" : tone === "edge" ? "#db9d70" : tone === "core" ? "#72b8df" : tone === "wan" ? "#bda77c" : "#91a9b6";
  return <g onClick={onClick} className="cursor-pointer"><rect x={x} y={y} width="105" height="44" fill="#101b22" stroke={color} strokeOpacity=".72" /><circle cx={x + 15} cy={y + 22} r="7" fill="none" stroke={color} /><text x={x + 29} y={y + 20} fill="#dce8ed" fontSize="9" fontWeight="600">{label}</text><text x={x + 29} y={y + 32} fill={color} fontSize="7">{icon.toUpperCase()}</text></g>;
}

export default Overview;
