import { Activity, AlertTriangle, ArrowDown, ArrowRight, Ban, Boxes, Cable, Check, ChevronRight, CircleDot, Clock3, Code2, Container, Cpu, Database, ExternalLink, FileCode2, Filter, Globe2, HardDrive, Info, Layers3, LockKeyhole, Menu, Network, Radio, RefreshCw, Router, Route as RouteIcon, Search, Server, Shield, SlidersHorizontal, TerminalSquare, Wifi, X, Zap, Square, Play, GitBranch, ListFilter, CircleDashed } from "lucide-react";
import { aclPolicies, configs, demoTelemetry, devices, events, links, navItems, topologyPositions, vlans, type DeviceRecord, type LinkRecord, type LinkState } from "@/lib/acmeData";
import { trpc } from "@/lib/trpc";
import { liveState, StatusDot, StateBadge, Icon, Panel, Header, Sidebar, PageHeader, StatCell } from "@/components/NetworkPrimitives";
import { RoutePath } from "@/components/RoutePath";
import { HistoryStrip } from "@/components/HistoryStrip";
import { ProtocolTable } from "./WanLab";
export function RoutingPage({ mode, live }: { mode: "DEMO" | "LIVE"; live: any }) { const telemetry = mode === "DEMO" ? demoTelemetry : live; return <div><PageHeader eyebrow="Protocols / Routing" title="Routing state" detail="BGP, OSPF, static route declarations, and the default-route path separated by runtime source." /><div className="grid gap-5 lg:grid-cols-2"><Panel title="BGP" eyebrow={`${mode} telemetry`}><ProtocolTable rows={[["Session", telemetry?.bgp?.state ?? "UNKNOWN"], ["Local AS", telemetry?.bgp?.localAs ? `AS${telemetry.bgp.localAs}` : "UNKNOWN"], ["Remote AS", telemetry?.bgp?.remoteAs ? `AS${telemetry.bgp.remoteAs}` : "UNKNOWN"], ["Neighbor", telemetry?.bgp?.neighbor ?? "UNKNOWN"], ["Prefixes received", String(telemetry?.bgp?.prefixesReceived ?? "UNKNOWN")], ["Prefixes sent", String(telemetry?.bgp?.prefixesSent ?? "UNKNOWN")], ["Uptime", telemetry?.bgp?.uptime ?? "UNKNOWN"], ["Route policy", telemetry?.bgp?.policy ?? "UNKNOWN"]]} /></Panel><Panel title="OSPF" eyebrow="Area 0"><ProtocolTable rows={[["State", telemetry?.ospf?.state ?? "UNKNOWN"], ["Router ID", telemetry?.ospf?.routerId ?? "UNKNOWN"], ["Area", telemetry?.ospf?.area ?? "0.0.0.0"], ["Neighbor", telemetry?.ospf?.neighbor ?? "UNKNOWN"], ["Network", telemetry?.ospf?.network ?? "UNKNOWN"], ["Default propagation", telemetry?.ospf?.defaultRoute ?? "UNKNOWN"]]} /></Panel></div><div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Static routes" eyebrow="Campus source model"><ProtocolTable rows={[["R1 default", "0.0.0.0/0 via 203.0.113.1"], ["ASA outside", "0.0.0.0/0 via 10.254.0.1"], ["ASA inside", "10.0.0.0/8 via 10.254.1.1"], ["CORE-SW1 default", "0.0.0.0/0 via 10.254.1.2"], ["OSPF", "10.0.0.0/8 area 0"]]} /></Panel><Panel title="Route path visualizer" eyebrow="0.0.0.0/0"><RoutePath telemetry={telemetry} mode={mode} /></Panel></div><div className="mt-5"><HistoryStrip mode={mode} /></div></div>; }

export default RoutingPage;
