import { Activity, AlertTriangle, ArrowDown, ArrowRight, Ban, Boxes, Cable, Check, ChevronRight, CircleDot, Clock3, Code2, Container, Cpu, Database, ExternalLink, FileCode2, Filter, Globe2, HardDrive, Info, Layers3, LockKeyhole, Menu, Network, Radio, RefreshCw, Router, Route as RouteIcon, Search, Server, Shield, SlidersHorizontal, TerminalSquare, Wifi, X, Zap, Square, Play, GitBranch, ListFilter, CircleDashed } from "lucide-react";
import { aclPolicies, configs, demoTelemetry, devices, events, links, navItems, topologyPositions, vlans, type DeviceRecord, type LinkRecord, type LinkState } from "@/lib/acmeData";
import { trpc } from "@/lib/trpc";
import { liveState, StatusDot, StateBadge, Icon, Panel, Header, Sidebar, PageHeader, StatCell } from "@/components/NetworkPrimitives";

const liveDevices = devices.filter((device) => device.site === "LIVE LAB");
const nodeById = Object.fromEntries(devices.map((device) => [device.id, device]));
export function WanLab({ mode, setMode, live, setSelected, go }: { mode: "DEMO" | "LIVE"; setMode: (mode: "DEMO" | "LIVE") => void; live: any; setSelected: (id: string) => void; go: (path: string) => void }) {
  const telemetry = mode === "DEMO" ? demoTelemetry : live;
  const online = mode === "DEMO" ? true : live?.reachable;
  return <div><PageHeader eyebrow="Operations / WAN Lab" title="Live WAN routing lab" detail="Real Docker + Containerlab + FRRouting topology. DEMO shows the known seeded state; LIVE queries the backend allowlist and reports unavailable data honestly." actions={<div className="flex items-center gap-2"><StateBadge label={`${mode} MODE`} state={mode === "DEMO" ? "modeled" : online ? "up" : "unknown"} /><button onClick={() => setMode(mode === "DEMO" ? "LIVE" : "DEMO")} className="flex items-center gap-2 border border-[#385467] bg-[#142532] px-3 py-2 text-[11px] text-[#b7dae9]"><RefreshCw size={14} /> Switch to {mode === "DEMO" ? "LIVE" : "DEMO"}</button></div>} />
    <div className="mb-5 grid gap-3 md:grid-cols-4"><LabMetric label="Docker" value={telemetry?.docker ?? "UNKNOWN"} detail="native engine / backend" state={telemetry?.docker} /><LabMetric label="Containerlab" value={telemetry?.containerlab ?? "UNKNOWN"} detail="acme-wan-lab" state={telemetry?.containerlab} /><LabMetric label="BGP" value={telemetry?.bgp?.state ?? "UNKNOWN"} detail="AS65001 ↔ AS65000" state={telemetry?.bgp?.state} /><LabMetric label="Default route" value={telemetry?.ospf?.defaultRoute ?? telemetry?.route?.state ?? "UNKNOWN"} detail="branch propagation" state={telemetry?.ospf?.defaultRoute ?? telemetry?.route?.state} /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(340px,.8fr)]"><Panel title="Protocol chain" eyebrow="Expected route flow"><WanDiagram telemetry={telemetry} onSelect={setSelected} /></Panel><Panel title="Live nodes" eyebrow={`${mode} · node inventory`}><div className="divide-y divide-[#20303a]">{(telemetry?.nodes ?? telemetry?.containers ?? liveDevices).map((node: any) => { const id = node.id ?? (node.name?.includes("isp") ? "isp-peer" : node.name?.includes("hq") ? "hq-r1" : "br-r1"); const d = nodeById[id]; return <button key={id} onClick={() => setSelected(id)} className="flex w-full items-center justify-between px-4 py-3 text-left hover:bg-[#121e26]"><div><div className="flex items-center gap-2 text-[12px] font-semibold text-[#d4e2e9]"><StatusDot state={node.state === "RUNNING" || d?.state === "up" ? "up" : "unknown"} />{d?.label ?? id}</div><div className="mono mt-1 text-[10px] text-[#708793]">{node.container ?? d?.model}</div></div><div className="text-right"><div className="mono text-[11px] text-[#9ccbe1]">{node.asn ? `AS${node.asn}` : d?.protocols?.join(" · ")}</div><div className="mt-1 text-[10px] text-[#6e8491]">{node.ip ?? d?.interfaces?.[0]?.ip ?? "—"}</div></div></button> })}</div></Panel></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel title="BGP session" eyebrow="Actual lab contract"><ProtocolTable rows={[["Local AS", telemetry?.bgp?.localAs ? `AS${telemetry.bgp.localAs}` : "UNKNOWN"], ["Remote AS", telemetry?.bgp?.remoteAs ? `AS${telemetry.bgp.remoteAs}` : "UNKNOWN"], ["Neighbor", telemetry?.bgp?.neighbor ?? "UNKNOWN"], ["Prefixes received", String(telemetry?.bgp?.prefixesReceived ?? "UNKNOWN")], ["Prefixes sent", String(telemetry?.bgp?.prefixesSent ?? "UNKNOWN")], ["Policy", telemetry?.bgp?.policy ?? "UNKNOWN"]]} /></Panel><Panel title="OSPF adjacency" eyebrow="Area 0"><ProtocolTable rows={[["Router ID", telemetry?.ospf?.routerId ?? "UNKNOWN"], ["Area", telemetry?.ospf?.area ?? "0.0.0.0"], ["Neighbor", telemetry?.ospf?.neighbor ?? "UNKNOWN"], ["Network", telemetry?.ospf?.network ?? "10.255.1.0/30"], ["Default route", telemetry?.ospf?.defaultRoute ?? "UNKNOWN"]]} /></Panel></div>
  </div>;
}

export function LabMetric({ label, value, detail, state }: { label: string; value: string; detail: string; state?: string }) { return <div className="panel p-4"><div className="mb-3 flex items-center justify-between"><span className="kicker">{label}</span><StatusDot state={state} /></div><div className="mono text-[18px] text-[#dfeef3]">{value}</div><div className="mt-1 text-[10px] text-[#708793]">{detail}</div></div>; }

export function WanDiagram({ telemetry, onSelect }: { telemetry: any; onSelect: (id: string) => void }) {
  const bgpUp = telemetry?.bgp?.state === "ESTABLISHED"; const ospfUp = telemetry?.ospf?.state === "FULL";
  return <div className="p-5"><div className="grid items-center gap-3 sm:grid-cols-[1fr_44px_1fr_44px_1fr]"><WanNode id="isp-peer" label="ISP PEER" detail="AS65000" ip="203.0.113.1" onSelect={onSelect} /><PathArrow label="eBGP" state={bgpUp ? "up" : "unknown"} /><WanNode id="hq-r1" label="HQ-R1" detail="AS65001" ip="203.0.113.2 · 10.255.1.1" onSelect={onSelect} /><PathArrow label="OSPF AREA 0" state={ospfUp ? "up" : "unknown"} /><WanNode id="br-r1" label="BR-R1" detail="10.255.1.2" ip="default route" onSelect={onSelect} /></div><div className="mt-6 border-t border-[#253640] pt-4"><RoutePath telemetry={telemetry} /></div></div>;
}

export function WanNode({ id, label, detail, ip, onSelect }: { id: string; label: string; detail: string; ip: string; onSelect: (id: string) => void }) { return <button onClick={() => onSelect(id)} className="border border-[#315366] bg-[#11212b] p-4 text-left hover:border-[#6eafd0]"><div className="mb-3 flex items-center justify-between"><Container size={17} className="text-[#6bd5a6]" /><StatusDot state="up" /></div><div className="text-[12px] font-bold tracking-[.1em] text-[#e1edf1]">{label}</div><div className="mono mt-2 text-[11px] text-[#75bddb]">{detail}</div><div className="mt-1 text-[10px] text-[#728a97]">{ip}</div></button>; }

export function PathArrow({ label, state }: { label: string; state: string }) { return <div className="flex flex-col items-center gap-2 text-center"><ArrowRight className={state === "up" ? "text-[#64d2a4]" : "text-[#8d7b50]"} size={20} /><span className="text-[9px] font-bold tracking-[.1em] text-[#93a7b2]">{label}</span></div>; }

export function RoutePath({ telemetry, mode, compact = false }: { telemetry: any; mode?: string; compact?: boolean }) { const present = telemetry?.ospf?.defaultRoute === "PRESENT" || telemetry?.route?.state === "PRESENT"; return <div className={`${compact ? "p-4" : ""}`}><div className="mb-4 flex items-center justify-between"><div><div className="kicker">Route path</div><div className="mono mt-1 text-[13px] text-[#dceaf0]">0.0.0.0/0</div></div><StateBadge label={present ? "PRESENT" : telemetry?.route?.state ?? "UNKNOWN"} state={present ? "up" : "unknown"} /></div><div className="flex items-center gap-1">{["ISP PEER", "eBGP", "HQ-R1", "OSPF", "BR-R1"].map((step, index) => <div key={step} className="flex min-w-0 flex-1 items-center gap-1"><div className={`min-w-0 flex-1 border px-2 py-2 text-center ${index % 2 === 1 ? "border-transparent" : present ? "border-[#2b735d] bg-[#10241f]" : "border-[#35434b] bg-[#131c22]"}`}><div className="truncate text-[9px] font-bold tracking-[.08em] text-[#b8cbd3]">{step}</div></div>{index < 4 && <ArrowRight size={12} className={present ? "shrink-0 text-[#5ccaa0]" : "shrink-0 text-[#677983]"} />}</div>)}</div>{!compact && <div className="mt-4 grid gap-2 border-t border-[#263743] pt-3 text-[10px] sm:grid-cols-4"><div><span className="data-label">Source</span><div className="mono mt-1 text-[#cbdbe3]">{telemetry?.route?.source ?? "UNKNOWN"}</div></div><div><span className="data-label">Protocol</span><div className="mono mt-1 text-[#cbdbe3]">{telemetry?.route?.protocol ?? "UNKNOWN"}</div></div><div><span className="data-label">Next hop</span><div className="mono mt-1 text-[#cbdbe3]">{telemetry?.route?.nextHop ?? "UNKNOWN"}</div></div><div><span className="data-label">Metric</span><div className="mono mt-1 text-[#cbdbe3]">{telemetry?.route?.metric ?? "UNKNOWN"}</div></div></div>}</div>; }

export function ProtocolTable({ rows }: { rows: string[][] }) { return <div className="divide-y divide-[#20303a]">{rows.map(([key, value]) => <div key={key} className="grid grid-cols-[minmax(130px,.7fr)_1.3fr] gap-3 px-4 py-2.5"><span className="data-label">{key}</span><span className="mono text-[11px] text-[#cbdbe3]">{value}</span></div>)}</div>; }

export default WanLab;
